server:
  port: 8099

 

zuul:
  
  prefix: /api
  routes:
    product catalog:
      path: /products/**
      serviceId: PRODUCTCATALOGAPPLICATION


      
spring:
  application:
    name: ApiGateway   
    
       
    
 

 

 

 
